### ISSUE TITLE
Odoo10 / Processmaker 3.2?

### ISSUE THREAD

**Issue by ndkazu** [ecdani/odooStep#2]
Are you planning to update to odoo10/ProcessMaker 3.2?

**Comment by ecdani** [comment]
It is still on development, but as far as i know, Odoo XML-RPC API is the same in both versions (9 and 10), and process maker 3.2 have no changes in plugin system. The update will probably consist on testing the plugin with those new versions.

**Comment by ndkazu** [comment]
Thank you for your answer!
Another question please: How do you install/use odooStep?
it is not a processmaker plugin, and it does not look like an Odoo addon....

**Comment by ecdani** [comment]
It's a Processmaker plugin, but i haven't made the installer yet. For now, if you want to use it, you need to deploy manually the code in your Processmaker installation.
It's explained briefly here: http://wiki.processmaker.com/3.0/Plugin_Development#Linking_the_Plugin_Files_into_ProcessMaker

You need to clone the repository, and link it (symlink) into _processmaker/workflow/engine/plugins/_

**Comment by ndkazu** [comment]
Hello, and thank you for answering my numerous questions.
Following your lead, I activated the plugin in ProcessMaker. The problem comes when after typing Odoo information in the Odoo section of the plugin I push the button to save the configuration: processmaker is just stucked on the updating display. Please keep me updated when you will test the plugin: odoo10/processmaker 3.2. I'm working on Windows 7.

regards,
Kazunobu

**Comment by ndkazu** [comment]
Ok I solved the problem!!
the easy answer is: DO NOT USE Internet explorer!!
using google chrome now and it is working fine!

Kazu
